services:
  rss-gateway:
    image: ghcr.io/batkiz/rss-gateway:latest
    pull_policy: always
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./configs/config.toml:/app/configs/config.toml:ro
